function matlab_official_pbch_bch_decode(inputMat, outputJson, outputMat)
%MATLAB_OFFICIAL_PBCH_BCH_DECODE Decode PBCH/BCH using MATLAB 5G Toolbox.
%
% This bridge intentionally keeps the standards-sensitive inverse chain in
% the official toolbox functions:
%   nrPBCHDecode  - TS 38.211 Section 7.3.3 inverse PBCH processing
%   nrBCHDecode   - TS 38.212 Section 7.1 BCH rate recovery, polar decode,
%                   CRC24C, payload descrambling and deinterleaving
%
% The input MAT file is generated by Python and must contain:
%   pbchEq, nIdCell, iSsbBar, noiseVar, listLength, lssbCandidates

in = load(inputMat);

pbchEq = in.pbchEq(:);
nCellID = double(in.nIdCell);
iSsbBar = double(in.iSsbBar);
if isfield(in, 'noiseVar')
    nVar = double(in.noiseVar);
else
    nVar = 1e-10;
end
if ~isfinite(nVar) || nVar < 0
    nVar = 1e-10;
end
if isfield(in, 'listLength')
    listLength = double(in.listLength);
else
    listLength = 8;
end
if isfield(in, 'lssbCandidates')
    lssbCandidates = double(in.lssbCandidates(:)).';
else
    lssbCandidates = [4 8];
end
lssbCandidates = lssbCandidates(ismember(lssbCandidates, [4 8 64]));
if isempty(lssbCandidates)
    lssbCandidates = [4 8];
end

attempts = repmat(emptyAttempt(), 0, 1);
bestIdx = 0;
bestScore = -Inf;

for lssb = lssbCandidates
    if lssb == 4
        primaryV = mod(iSsbBar, 4);
    else
        primaryV = mod(iSsbBar, 8);
    end
    vCandidates = unique([primaryV, 0:7], 'stable');

    for v = vCandidates
        attempt = emptyAttempt();
        attempt.lssb = double(lssb);
        attempt.v = double(v);
        attempt.nVar = double(nVar);
        try
            bchSoft = nrPBCHDecode(pbchEq, nCellID, v, nVar);
            [scrblk, errFlag, trblk, sfn4lsb, hrf, msbidxoffset] = nrBCHDecode( ...
                bchSoft, listLength, lssb, nCellID);

            attempt.crcOk = ~logical(errFlag);
            attempt.errFlag = logical(errFlag);
            attempt.failureStage = ternary(attempt.crcOk, '', 'crc');
            attempt.meanAbsSoft = finiteScalar(mean(abs(bchSoft)));
            attempt.maxAbsSoft = finiteScalar(max(abs(bchSoft)));
            attempt.scrambledBlockBits = double(scrblk(:)).';
            attempt.mibBits = double(trblk(:)).';
            attempt.sfnLsb4 = double(sfn4lsb(:)).';
            attempt.hrf = double(hrf);
            attempt.msbIdxOffset = double(msbidxoffset(:)).';
            attempt.mib = parseMibBits(trblk, sfn4lsb, hrf, msbidxoffset, lssb);
        catch ex
            attempt.crcOk = false;
            attempt.errFlag = true;
            attempt.failureStage = 'matlab_official';
            attempt.error = ex.message;
        end

        attempts(end + 1) = attempt; %#ok<AGROW>
        score = double(attempt.crcOk) * 1e9 + attempt.meanAbsSoft - double(attempt.errFlag) * 1e3;
        if score > bestScore
            bestScore = score;
            bestIdx = numel(attempts);
        end
    end
end

if bestIdx == 0
    best = emptyAttempt();
    best.failureStage = 'matlab_official';
    best.error = 'No official decode attempts were evaluated';
else
    best = attempts(bestIdx);
end

result = struct();
result.method = 'matlab_5g_toolbox_nrPBCHDecode_nrBCHDecode';
result.officialChain = true;
result.standardReferences = {'TS 38.211 Section 7.3.3', ...
    'TS 38.212 Section 7.1', 'TS 38.331 Section 6.2'};
result.inputMat = char(inputMat);
result.nIdCell = double(nCellID);
result.iSsbBar = double(iSsbBar);
result.noiseVar = double(nVar);
result.listLength = double(listLength);
result.lssbCandidates = double(lssbCandidates);
result.pbchEqCount = double(numel(pbchEq));
result.crcOk = logical(best.crcOk);
result.failureStage = best.failureStage;
result.bestAttempt = best;
result.attempts = attempts;
result.matlabVersion = version;
result.toolbox = '5G Toolbox';

if nargin >= 3 && ~isempty(outputMat)
    save(outputMat, 'result', 'attempts');
end

jsonText = jsonencode(result, PrettyPrint=true);
fid = fopen(outputJson, 'w');
if fid < 0
    error('Could not open output JSON: %s', outputJson);
end
cleanupObj = onCleanup(@() fclose(fid));
fwrite(fid, jsonText, 'char');

fprintf('Official PBCH/BCH decode done: CRC=%d, Lssb=%d, v=%d\n', ...
    result.crcOk, best.lssb, best.v);
end

function attempt = emptyAttempt()
attempt = struct();
attempt.lssb = NaN;
attempt.v = NaN;
attempt.nVar = NaN;
attempt.crcOk = false;
attempt.errFlag = true;
attempt.failureStage = '';
attempt.error = '';
attempt.meanAbsSoft = 0;
attempt.maxAbsSoft = 0;
attempt.scrambledBlockBits = [];
attempt.mibBits = [];
attempt.sfnLsb4 = [];
attempt.hrf = NaN;
attempt.msbIdxOffset = [];
attempt.mib = struct();
end

function mib = parseMibBits(trblk, sfn4lsb, hrf, msbidxoffset, lssb)
bits = double(trblk(:));
if numel(bits) < 24
    bits = [bits; zeros(24 - numel(bits), 1)];
end

sfnMsb6 = bitsToInt(bits(2:7));
sfnLsb = bitsToInt(double(sfn4lsb(:)));
sfn10 = sfnMsb6 * 16 + sfnLsb;
kSsbLsb4 = bitsToInt(bits(9:12));
if lssb == 64
    ssbIndexMsb3 = bitsToInt(double(msbidxoffset(:)));
    kSsbMsb = NaN;
else
    ssbIndexMsb3 = NaN;
    kSsbMsb = bitsToInt(double(msbidxoffset(:)));
end

mib = struct();
mib.messageTypeBit = double(bits(1));
mib.systemFrameNumberMsb6 = double(sfnMsb6);
mib.systemFrameNumberLsb4 = double(sfnLsb);
mib.systemFrameNumber10 = double(sfn10);
mib.subCarrierSpacingCommonBit = double(bits(8));
mib.subCarrierSpacingCommon = scsCommonLabel(bits(8), lssb);
mib.ssbSubcarrierOffsetLsb4 = double(kSsbLsb4);
mib.kSsbMsb = double(kSsbMsb);
mib.kSsb = double(kSsbLsb4 + 16 * finiteZero(kSsbMsb));
mib.ssbIndexMsb3 = double(ssbIndexMsb3);
mib.dmrsTypeAPosition = double(2 + bits(13));
mib.pdcchConfigSIB1 = double(bitsToInt(bits(14:21)));
mib.cellBarredBit = double(bits(22));
mib.cellBarred = ternary(bits(22) == 0, 'barred', 'notBarred');
mib.intraFreqReselectionBit = double(bits(23));
mib.intraFreqReselection = ternary(bits(23) == 0, 'allowed', 'notAllowed');
mib.spareBit = double(bits(24));
mib.rawMibBits = double(bits(1:24)).';
end

function out = bitsToInt(bits)
bits = double(bits(:));
out = 0;
for ii = 1:numel(bits)
    out = out * 2 + double(bits(ii) ~= 0);
end
end

function label = scsCommonLabel(bit, lssb)
if lssb == 64
    if bit == 0
        label = 'scs60';
    else
        label = 'scs120';
    end
else
    if bit == 0
        label = 'scs15';
    else
        label = 'scs30';
    end
end
end

function out = finiteScalar(value)
out = double(value);
if isempty(out) || ~isfinite(out)
    out = 0;
end
end

function out = finiteZero(value)
if isempty(value) || ~isfinite(value)
    out = 0;
else
    out = double(value);
end
end

function out = ternary(condition, yesValue, noValue)
if condition
    out = yesValue;
else
    out = noValue;
end
end
